/* ============================================
   Crown Paints — Complete Colour Library
   All 194 colours from crownpaints.com
   ============================================ */

const colourData = [
  // ─── WHITES ─────────────────────────────────
  { name: "Pure Brilliant White", hex: '#F3F3ED', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "White", hex: '#FFFFFF', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Fresh Coconut", hex: '#ECECE9', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Best China", hex: '#EEEFEA', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Chalky White", hex: '#E9EBE9', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Gallery Wall", hex: '#EBECEB', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Sail White", hex: '#EEEBE5', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Woven Calico", hex: '#EDEDE5', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Canvas White", hex: '#F1EFE6', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Milk Bottle", hex: '#F1F4E9', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Milk White", hex: '#F2F4EC', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Cotton Cloth", hex: '#E7E8E4', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Clay White", hex: '#E9EBED', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },
  { name: "Writing Paper", hex: '#E4E7E2', category: 'Whites', tone: 'Light', brand: 'Crown Paints' },

  // ─── CREAMS ─────────────────────────────────
  { name: "Cotton Belt", hex: '#F0EFE1', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Cream White", hex: '#F4EEE1', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Collector's White", hex: '#F4F0E0', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Swan Feather", hex: '#F1ECE1', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Beige White", hex: '#EAE4D8', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Chalk Hill", hex: '#E6E1D6', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "New Chapter", hex: '#EBDFCF', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Antique Cream", hex: '#E8E1D2', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Soft Linen", hex: '#F8F3E0', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Ivory Cream", hex: '#F5E8D4', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Magnolia", hex: '#F4E4CE', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Ivory Stone", hex: '#F0E2CB', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Soft Cream", hex: '#FCE3C6', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Cornish Cream", hex: '#F5E8C5', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Almond Cream", hex: '#E6DBC9', category: 'Creams', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Light Cream", hex: '#F2DABE', category: 'Creams', tone: 'Light', brand: 'Crown Paints' },
  { name: "Toasted Almond", hex: '#D9C8B8', category: 'Creams', tone: 'Mid', brand: 'Crown Paints' },

  // ─── NEUTRALS ───────────────────────────────
  { name: "Gentle Hush", hex: '#CDC8BC', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Recipe Book", hex: '#DAD3C8', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Quiet Time", hex: '#DEDDDE', category: 'Neutrals', tone: 'Light', brand: 'Crown Paints' },
  { name: "Organic Cloth", hex: '#E7E1DB', category: 'Neutrals', tone: 'Light', brand: 'Crown Paints' },
  { name: "Clay Like", hex: '#D5D0C9', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Dash Of Nutmeg", hex: '#D5D0C9', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "White Pepper", hex: '#DACEC2', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Soaring Dove", hex: '#E3E1DB', category: 'Neutrals', tone: 'Light', brand: 'Crown Paints' },
  { name: "Snowfall", hex: '#DED9D0', category: 'Neutrals', tone: 'Light', brand: 'Crown Paints' },
  { name: "Afternoon Tea", hex: '#DED2C3', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Wheatgrass", hex: '#DED2C3', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Sandblast", hex: '#E2D6C5', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Sandstone", hex: '#DBCAB5', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Country Stone", hex: '#DFD0BC', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Mid Stone", hex: '#BFAD96', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "East Village", hex: '#CDC1B4', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Reframed", hex: '#CEC3B2', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Sewing Bee", hex: '#D2B88F', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Drawing Board", hex: '#C5BAAE', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Picnic Basket", hex: '#B9A594', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Rustic Twine", hex: '#C5A887', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Potted History", hex: '#A0958A', category: 'Neutrals', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Linen Blend", hex: '#D2C8BF', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Hare", hex: '#CABBB4', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Market Day", hex: '#C3AEA3', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "One of a Kind", hex: '#B19386', category: 'Neutrals', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Mulberry Mist", hex: '#D1C6C7', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Vintage Crush", hex: '#B7A49F', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Powdered Clay", hex: '#CEA89C', category: 'Neutrals', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Bitter Chocolate", hex: '#61554F', category: 'Neutrals', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Chestnut Brown", hex: '#5C443E', category: 'Neutrals', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Leatherbound", hex: '#514A4D', category: 'Neutrals', tone: 'Deep', brand: 'Crown Paints' },

  // ─── PINKS ──────────────────────────────────
  { name: "Candy Clay", hex: '#BF8878', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Crème de la Rose", hex: '#F0E6E4', category: 'Pinks', tone: 'Light', brand: 'Crown Paints' },
  { name: "Softly Does It", hex: '#EBE2E1', category: 'Pinks', tone: 'Light', brand: 'Crown Paints' },
  { name: "Quiet Space", hex: '#E4DED8', category: 'Pinks', tone: 'Light', brand: 'Crown Paints' },
  { name: "Music Box", hex: '#D9CCCC', category: 'Pinks', tone: 'Light', brand: 'Crown Paints' },
  { name: "Somerset Pink", hex: '#F6E5E5', category: 'Pinks', tone: 'Light', brand: 'Crown Paints' },
  { name: "Fairy Dust", hex: '#EED5DD', category: 'Pinks', tone: 'Light', brand: 'Crown Paints' },
  { name: "Pashmina", hex: '#E0CECC', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Soft Blossom", hex: '#CBC6CA', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Le Petit Palais", hex: '#DEBAB7', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Raspberry Souffle", hex: '#D1B7BD', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Cross Stitch", hex: '#BD9A97', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Vintage Pink", hex: '#BD9A97', category: 'Pinks', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Always Orchid", hex: '#B0908C', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Rhubarb Rose", hex: '#B57378', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Made With Love", hex: '#A96C76', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Ceramic Kiln", hex: '#B06458', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Crimson Fox", hex: '#A45849', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Terracotta", hex: '#A85A53', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Grape Escape", hex: '#7E6668', category: 'Pinks', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Brick Red", hex: '#925C4F', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Pillar Box Red", hex: '#A8413C', category: 'Pinks', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Classic Burgundy", hex: '#733539', category: 'Pinks', tone: 'Deep', brand: 'Crown Paints' },

  // ─── YELLOWS ────────────────────────────────
  { name: "Pale Gold", hex: '#F8D5A7', category: 'Yellows', tone: 'Light', brand: 'Crown Paints' },
  { name: "Egyptian Sand", hex: '#ECCCA0', category: 'Yellows', tone: 'Light', brand: 'Crown Paints' },
  { name: "Sunrise", hex: '#FFE6AB', category: 'Yellows', tone: 'Light', brand: 'Crown Paints' },
  { name: "Happy Daze", hex: '#FFDF85', category: 'Yellows', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Mustard Jar", hex: '#E7BD67', category: 'Yellows', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Overjoyed", hex: '#D3A764', category: 'Yellows', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Yarn", hex: '#CCA54F', category: 'Yellows', tone: 'Rich', brand: 'Crown Paints' },

  // ─── GREENS ─────────────────────────────────
  { name: "Woodland Wanderer", hex: '#535F55', category: 'Greens', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Botanical Extract", hex: '#E2EAE3', category: 'Greens', tone: 'Light', brand: 'Crown Paints' },
  { name: "Willow Breeze", hex: '#CFD6D0', category: 'Greens', tone: 'Light', brand: 'Crown Paints' },
  { name: "Poetry", hex: '#D4D4C1', category: 'Greens', tone: 'Light', brand: 'Crown Paints' },
  { name: "Spice Rack", hex: '#C5D0BE', category: 'Greens', tone: 'Light', brand: 'Crown Paints' },
  { name: "Sow Good", hex: '#B9C0B0', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Mellow Sage", hex: '#B9C0B0', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Bay Tree", hex: '#A8AE99', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Light Fern", hex: '#B5B09A', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Craft Fair", hex: '#9FAD9B', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Olive", hex: '#8C907F', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Evergreen Echo", hex: '#8B927D', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Family Tree", hex: '#6F796B', category: 'Greens', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Collage", hex: '#4D6C66', category: 'Greens', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Ivy Grey", hex: '#77938E', category: 'Greens', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Botany Bay", hex: '#6A8886', category: 'Greens', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Emerald Vision", hex: '#21645D', category: 'Greens', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Endeavour", hex: '#435C64', category: 'Greens', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Racing Green", hex: '#3E4945', category: 'Greens', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Fern Canopy", hex: '#717A6F', category: 'Greens', tone: 'Rich', brand: 'Crown Paints' },

  // ─── BLUES ──────────────────────────────────
  { name: "Moonlight Bay", hex: '#CFDFEC', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },
  { name: "Watermark", hex: '#CAD6D7', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },
  { name: "Soft Wave", hex: '#BBC9CC', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },
  { name: "Blue Glaze", hex: '#BAC7D0', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },
  { name: "Powder Blue", hex: '#B0CFE6', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },
  { name: "Soft Duck Egg", hex: '#B3CEC5', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },
  { name: "Stepping Stone", hex: '#AAC5C5', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Gentle Blue", hex: '#9BB7BD', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Duck Egg", hex: '#9BB7BD', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Scrapbook", hex: '#90AEB9', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Simply Duck Egg", hex: '#94A8AA', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Curiosity", hex: '#94A8AA', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Feeling Free", hex: '#8EA2B2', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Silver Blue", hex: '#8F9CAF', category: 'Blues', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Button Box", hex: '#648186', category: 'Blues', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Teal", hex: '#4B8394', category: 'Blues', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Runaway", hex: '#627787', category: 'Blues', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Palm Springs", hex: '#00878C', category: 'Blues', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Bright Bluejay", hex: '#47669E', category: 'Blues', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Abstract Art", hex: '#396A88', category: 'Blues', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Indulgence", hex: '#536C7D', category: 'Blues', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Genuine", hex: '#4A646D', category: 'Blues', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Oxford Blue", hex: '#2F4C6C', category: 'Blues', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Midnight Navy", hex: '#3B4A5B', category: 'Blues', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Printworks", hex: '#4D5961', category: 'Blues', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Morning Sky", hex: '#B0C3D5', category: 'Blues', tone: 'Light', brand: 'Crown Paints' },

  // ─── GREYS ──────────────────────────────────
  { name: "Seldom Seen", hex: '#E4E7E2', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Early Dawn", hex: '#E0E0DC', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Soft Steel", hex: '#DCDFE1', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Splash Of Pepper", hex: '#DCDFE1', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Sugar Bowl", hex: '#DADAD5', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Spotlight", hex: '#DDDAD9', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Sketch Pad", hex: '#D4D6D6', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Soft Scribbles", hex: '#D3D0CB', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Salt Spray", hex: '#CCCDC9', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Grey Putty", hex: '#C8C6BD', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Pacific Oyster", hex: '#CACDCC', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Clean Slate", hex: '#C5C6CA', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Neighbourhood", hex: '#BDBDB9', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Cloud Burst", hex: '#C7C3C1', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Gravel", hex: '#C7C3C1', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Linen Cupboard", hex: '#C7C3C1', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Light Grey", hex: '#C1C0BA', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Marble Top", hex: '#BDC7C4', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Needles & Pins", hex: '#C0C4C3', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Cloudy Day", hex: '#B7BCB7', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Plymouth Grey", hex: '#BDB8B2', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Memory Lane", hex: '#A6A6A4', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Granite Dust", hex: '#A6A6A4', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "French Grey", hex: '#AFA692', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Blue Gravel", hex: '#969CA4', category: 'Greys', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Dark Stone", hex: '#9C9181', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Quarried Stone", hex: '#918C89', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "City Break", hex: '#7B8082', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Vermont Grey", hex: '#7B818C', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Calligraphy", hex: '#757572', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Tin Bath", hex: '#707377', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Seclusion", hex: '#6B7376', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Slate Grey", hex: '#657175', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Aftershow", hex: '#595C64', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Smokey Grey", hex: '#5C5F60', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Anthracite", hex: '#494D52', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Rebel", hex: '#393939', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Jet Black", hex: '#393939', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Black", hex: '#393939', category: 'Greys', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Sophistication", hex: '#CFD1D1', category: 'Greys', tone: 'Light', brand: 'Crown Paints' },
  { name: "Chocolate", hex: '#8E7F74', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Dark Grey", hex: '#747D80', category: 'Greys', tone: 'Rich', brand: 'Crown Paints' },

  // ─── METALLICS ──────────────────────────────
  { name: "Copper", hex: '#CE9C76', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Entice", hex: '#BCB1A5', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Fawn", hex: '#D7C7B6', category: 'Metallics', tone: 'Light', brand: 'Crown Paints' },
  { name: "Granite Top", hex: '#696C6E', category: 'Metallics', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Mid Grey", hex: '#8D96A0', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Millionaire", hex: '#B7946D', category: 'Metallics', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Pewter", hex: '#9CA2A7', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Rose Gold", hex: '#C99892', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Saddle Stitch", hex: '#A77E65', category: 'Metallics', tone: 'Rich', brand: 'Crown Paints' },
  { name: "Soft Grey", hex: '#BCBAB9', category: 'Metallics', tone: 'Light', brand: 'Crown Paints' },
  { name: "Taupe", hex: '#C3B0A0', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },
  { name: "Work of Art", hex: '#525859', category: 'Metallics', tone: 'Deep', brand: 'Crown Paints' },
  { name: "Striking", hex: '#C8B290', category: 'Metallics', tone: 'Mid', brand: 'Crown Paints' },

  // ─── FARROW & BALL ────────────────────────
  { name: "Wimborne White", hex: '#F4F1E6', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/wimborne-white' },
  { name: "All White", hex: '#F6F7F2', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/all-white' },
  { name: "Pointing", hex: '#F8F5EA', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pointing' },
  { name: "Skimming Stone", hex: '#E3DCD1', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/skimming-stone' },
  { name: "Elephant's Breath", hex: '#CAC3B7', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/elephants-breath' },
  { name: "School House White", hex: '#E1DBCD', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/school-house-white' },
  { name: "Setting Plaster", hex: '#E1C8B5', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/setting-plaster' },
  { name: "Dimity", hex: '#E8E0CF', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dimity' },
  { name: "Slipper Satin", hex: '#E7E1D3', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/slipper-satin' },
  { name: "French Gray", hex: '#ADAC98', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/french-gray' },
  { name: "Green Smoke", hex: '#768277', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/green-smoke' },
  { name: "Shaded White", hex: '#D9D3C3', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/shaded-white' },
  { name: "Strong White", hex: '#E3E0DA', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/strong-white' },
  { name: "Wevet", hex: '#EDEAE6', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/wevet' },
  { name: "Ammonite", hex: '#DCD8D1', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ammonite' },
  { name: "Drop Cloth", hex: '#BEB7A5', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/drop-cloth' },
  { name: "Joa's White", hex: '#D8CBB6', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/joas-white' },
  { name: "Stirabout", hex: '#DAD1C5', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/stirabout' },
  { name: "Hague Blue", hex: '#43525B', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hague-blue' },
  { name: "Scallop", hex: '#D7C4B4', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/scallop' },
  { name: "Blackened", hex: '#D8D9D8', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blackened' },
  { name: "Cornforth White", hex: '#CBC7BF', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cornforth-white' },
  { name: "Dimpse", hex: '#D7D7D5', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dimpse' },
  { name: "Purbeck Stone", hex: '#B9B6AD', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/purbeck-stone' },
  { name: "Pavilion Gray", hex: '#BFBBB5', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pavilion-gray' },
  { name: "Shadow White", hex: '#D1CBB7', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/shadow-white' },
  { name: "Dove Tale", hex: '#BCB5AE', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dove-tale' },
  { name: "Lime White", hex: '#E1DAC3', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lime-white' },
  { name: "Off-White", hex: '#D8D2B9', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/off-white' },
  { name: "Oxford Stone", hex: '#CBBCA6', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/oxford-stone' },
  { name: "Old White", hex: '#C2BAA5', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/old-white' },
  { name: "James White", hex: '#E8E6D5', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/james-white' },
  { name: "Jitney", hex: '#BAAC9D', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/jitney' },
  { name: "White Tie", hex: '#EFE9D6', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/white-tie' },
  { name: "London Stone", hex: '#B8A996', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/london-stone' },
  { name: "New White", hex: '#EEE5CB', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/new-white' },
  { name: "Dead Salmon", hex: '#B6A294', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dead-salmon' },
  { name: "Matchstick", hex: '#E0D2B6', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/matchstick' },
  { name: "Stony Ground", hex: '#CDC4B1', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/stony-ground' },
  { name: "String", hex: '#DBCFB4', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/string' },
  { name: "Light Gray", hex: '#A89D89', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/light-gray' },
  { name: "Cord", hex: '#D2C3A2', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cord' },
  { name: "Mouse's Back", hex: '#998E79', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/mouses-back' },
  { name: "Cromarty", hex: '#CACABE', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cromarty' },
  { name: "Bone", hex: '#CAC5B0', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bone' },
  { name: "Mizzle", hex: '#B9BBAC', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/mizzle' },
  { name: "Hardwick White", hex: '#B7B2A6', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hardwick-white' },
  { name: "Blue Gray", hex: '#B3B8AA', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blue-gray' },
  { name: "Sizing", hex: '#E1E9EB', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sizing' },
  { name: "Lamp Room Gray", hex: '#ABAAA2', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lamp-room-gray' },
  { name: "Pigeon", hex: '#9DA298', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pigeon' },
  { name: "Manor House Gray", hex: '#A5A7A4', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/manor-house-gray' },
  { name: "Eddy", hex: '#CDCFBF', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/eddy' },
  { name: "Plummett", hex: '#949796', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/plummett' },
  { name: "Treron", hex: '#747667', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/treron' },
  { name: "Worsted", hex: '#A19D98', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/worsted' },
  { name: "Mole's Breath", hex: '#898582', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/moles-breath' },
  { name: "Great White", hex: '#E2DEDA', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/great-white' },
  { name: "Tailor Tack", hex: '#F8EEE4', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/tailor-tack' },
  { name: "Peignoir", hex: '#D1C3BF', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/peignoir' },
  { name: "Middleton Pink", hex: '#F5E3E3', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/middleton-pink' },
  { name: "Calluna", hex: '#CDCBD0', category: 'Purples', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/calluna' },
  { name: "Calamine", hex: '#E4D3CC', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/calamine' },
  { name: "Brassica", hex: '#958C94', category: 'Purples', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/brassica' },
  { name: "Cinder Rose", hex: '#C6A7AD', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cinder-rose' },
  { name: "Pelt", hex: '#564852', category: 'Purples', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pelt' },
  { name: "Sulking Room Pink", hex: '#A78B87', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sulking-room-pink' },
  { name: "Paean Black", hex: '#423F45', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/paean-black' },
  { name: "Charleston Gray", hex: '#A1978F', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/charleston-gray' },
  { name: "Broccoli Brown", hex: '#8B7C68', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/broccoli-brown' },
  { name: "Dibber", hex: '#857E60', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dibber' },
  { name: "Reduced Green", hex: '#5D5B4D', category: 'Darks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/reduced-green' },
  { name: "Tanner's Brown", hex: '#544F4F', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/tanners-brown' },
  { name: "London Clay", hex: '#776A63', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/london-clay' },
  { name: "Pink Ground", hex: '#ECD8CA', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pink-ground' },
  { name: "Red Earth", hex: '#C48472', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/red-earth' },
  { name: "Picture Gallery Red", hex: '#9F5C51', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/picture-gallery-red' },
  { name: "Templeton Pink", hex: '#D1B7A3', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/templeton-pink' },
  { name: "Naperon", hex: '#DAA990', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/naperon' },
  { name: "Bamboozle", hex: '#AA5B4E', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bamboozle' },
  { name: "Nancy's Blushes", hex: '#EAB3B3', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/nancys-blushes' },
  { name: "Charlotte's Locks", hex: '#D26442', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/charlottes-locks' },
  { name: "Rangwali", hex: '#BC8093', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/rangwali' },
  { name: "Eating Room Red", hex: '#925253', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/eating-room-red' },
  { name: "Marmelo", hex: '#AA7652', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/marmelo' },
  { name: "Etruscan Red", hex: '#87584D', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/etruscan-red' },
  { name: "Rectory Red", hex: '#A54551', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/rectory-red' },
  { name: "Preference Red", hex: '#664046', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/preference-red' },
  { name: "Incarnadine", hex: '#A24A4B', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/incarnadine' },
  { name: "Brinjal", hex: '#61464B', category: 'Purples', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/brinjal' },
  { name: "Stiffkey Blue", hex: '#4B5D6C', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/stiffkey-blue' },
  { name: "Borrowed Light", hex: '#D4DDDE', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/borrowed-light' },
  { name: "Skylight", hex: '#CBD0CE', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/skylight' },
  { name: "Down Pipe", hex: '#666C6C', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/down-pipe' },
  { name: "Light Blue", hex: '#AFB5AD', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/light-blue' },
  { name: "Hopper Head", hex: '#55595C', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hopper-head' },
  { name: "Oval Room Blue", hex: '#7E9292', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/oval-room-blue' },
  { name: "Railings", hex: '#4A4E51', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/railings' },
  { name: "Selvedge", hex: '#81949B', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/selvedge' },
  { name: "Off-Black", hex: '#47494B', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/off-black' },
  { name: "De Nimes", hex: '#6E8083', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/de-nimes' },
  { name: "Pitch Black", hex: '#424041', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pitch-black' },
  { name: "Inchyra Blue", hex: '#48595A', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/inchyra-blue' },
  { name: "Cabbage White", hex: '#E5ECEA', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cabbage-white' },
  { name: "Kakelugn", hex: '#C9D4DA', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/kakelugn' },
  { name: "Blue Ground", hex: '#A7C9CD', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blue-ground' },
  { name: "Pale Powder", hex: '#D2D8CD', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pale-powder' },
  { name: "Parma Gray", hex: '#A9B8C0', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/parma-gray' },
  { name: "Teresa's Green", hex: '#C2D0C7', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/teresas-green' },
  { name: "Lulworth Blue", hex: '#A5BCCB', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lulworth-blue' },
  { name: "Green Blue", hex: '#AFC1B6', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/green-blue' },
  { name: "Kittiwake", hex: '#8FA5B3', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/kittiwake' },
  { name: "Dix Blue", hex: '#9DB4B1', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dix-blue' },
  { name: "Cook's Blue", hex: '#6F93B4', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cooks-blue' },
  { name: "Arsenic", hex: '#8AB6A2', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/arsenic' },
  { name: "Wine Dark", hex: '#636C7D', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/wine-dark' },
  { name: "Vardo", hex: '#478789', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/vardo' },
  { name: "Stone Blue", hex: '#7A9DA7', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/stone-blue' },
  { name: "Whirlybird", hex: '#A6B89B', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/whirlybird' },
  { name: "Green Ground", hex: '#D8D9BA', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/green-ground' },
  { name: "Breakfast Room Green", hex: '#94A88C', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/breakfast-room-green' },
  { name: "Cooking Apple Green", hex: '#C3C5A7', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cooking-apple-green' },
  { name: "Yeabridge Green", hex: '#8B9E76', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/yeabridge-green' },
  { name: "Sap Green", hex: '#798155', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sap-green' },
  { name: "Ball Green", hex: '#BBB69B', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ball-green' },
  { name: "Calke Green", hex: '#7D8D73', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/calke-green' },
  { name: "Vert de Terre", hex: '#BCBFAA', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/vert-de-terre' },
  { name: "Beverly", hex: '#546252', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/beverly' },
  { name: "Lichen", hex: '#93977E', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lichen' },
  { name: "Bancha", hex: '#656C4D', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bancha' },
  { name: "Card Room Green", hex: '#8C9385', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/card-room-green' },
  { name: "Douter", hex: '#66736A', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/douter' },
  { name: "Studio Green", hex: '#4B5250', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/studio-green' },
  { name: "Tallow", hex: '#F6EBD2', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/tallow' },
  { name: "Dayroom Yellow", hex: '#F1DF9D', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dayroom-yellow' },
  { name: "Farrow's Cream", hex: '#EADBB9', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/farrows-cream' },
  { name: "Citron", hex: '#EED086', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/citron' },
  { name: "Dorset Cream", hex: '#EBD3A8', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dorset-cream' },
  { name: "Yellow Ground", hex: '#EECE8E', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/yellow-ground' },
  { name: "Hay", hex: '#DBC79C', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hay' },
  { name: "Babouche", hex: '#E8C46C', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/babouche' },
  { name: "Sudbury Yellow", hex: '#DABA7E', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sudbury-yellow' },
  { name: "India Yellow", hex: '#C9A364', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/india-yellow' },
  { name: "Duster", hex: '#BFA371', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/duster' },
  { name: "Au Lait", hex: '#E9E6DA', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/au-lait' },
  { name: "Blue Maize", hex: '#444B6D', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blue-maize' },
  { name: "Cardamom", hex: '#6B6550', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cardamom' },
  { name: "Hog Plum", hex: '#E2E59F', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hog-plum' },
  { name: "Liquorice", hex: '#4D4B4C', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/liquorice' },
  { name: "Lobster", hex: '#5BAABB', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lobster' },
  { name: "Pea Flower Tea", hex: '#4485BA', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pea-flower-tea' },
  { name: "Raw Tomatillo", hex: '#77A367', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/raw-tomatillo' },
  { name: "Roasted Macadamia", hex: '#CDC1B0', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/roasted-macadamia' },
  { name: "Romesco", hex: '#BF4E4A', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/romesco' },
  { name: "Sardine", hex: '#98AAAC', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sardine' },
  { name: "Shallot", hex: '#DDAAC2', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/shallot' },
  { name: "Clunch", hex: '#E0DAC7', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/clunch' },
  { name: "Farrow's White", hex: '#E8E3D3', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/farrows-white' },
  { name: "Blanc De Treillage", hex: '#E1DACB', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blanc-de-treillage' },
  { name: "Turret White", hex: '#D6CEBA', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/turret-white' },
  { name: "Ringwold Ground", hex: '#EADEC5', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ringwold-ground' },
  { name: "Archive", hex: '#D9C9B5', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/archive' },
  { name: "Single Cream", hex: '#E8D7BF', category: 'Neutrals', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/single-cream' },
  { name: "Light Sand", hex: '#E3D8C2', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/light-sand' },
  { name: "Orange Coloured White", hex: '#E5D7B9', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/orange-coloured-white' },
  { name: "Double Cream", hex: '#E5CEAC', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/double-cream' },
  { name: "Salt", hex: '#ECEBE7', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/salt' },
  { name: "Blanc De Chine", hex: '#CFD3C9', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blanc-de-chine' },
  { name: "Shadow Gray", hex: '#D0CDC0', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/shadow-gray' },
  { name: "Vichyssoise", hex: '#D4D4BC', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/vichyssoise' },
  { name: "Fawn", hex: '#C2B79C', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/fawn' },
  { name: "Vitty Green", hex: '#B4B1A4', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/vitty-green' },
  { name: "Wall White", hex: '#C5BDA9', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/wall-white' },
  { name: "Skimmed Milk White", hex: '#D7D1BC', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/skimmed-milk-white' },
  { name: "Chemise", hex: '#A09990', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/chemise' },
  { name: "Stoke", hex: '#9C9892', category: 'Greys', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/stoke' },
  { name: "Savage Ground", hex: '#DCCCB0', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/savage-ground' },
  { name: "Light Stone", hex: '#CFC2A2', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/light-stone' },
  { name: "Templa White", hex: '#ECD7AF', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/templa-white' },
  { name: "Cream", hex: '#E6D4AC', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cream' },
  { name: "Cats Paw", hex: '#C8B491', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cats-paw' },
  { name: "Biscuit", hex: '#BFAC8A', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/biscuit' },
  { name: "Broccoli Brown", hex: '#8B7C68', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/broccoli-brown' },
  { name: "Buff", hex: '#B9A48B', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/buff' },
  { name: "Planter", hex: '#B9A78E', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/planter' },
  { name: "Ash Grey", hex: '#BFBCA8', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ash-grey' },
  { name: "Stone White", hex: '#B7B295', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/stone-white' },
  { name: "Olive", hex: '#969576', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/olive' },
  { name: "Green Stone", hex: '#9E9674', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/green-stone' },
  { name: "Drab", hex: '#9D8D72', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/drab' },
  { name: "Tack Room Door", hex: '#A0846A', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/tack-room-door' },
  { name: "Dauphin", hex: '#998971', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dauphin' },
  { name: "Salon Drab", hex: '#746859', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/salon-drab' },
  { name: "Pantalon", hex: '#625A49', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pantalon' },
  { name: "Wainscot", hex: '#816751', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/wainscot' },
  { name: "Sugared Almond", hex: '#D1C2CE', category: 'Purples', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sugared-almond' },
  { name: "Pink Drab", hex: '#CFBBB4', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pink-drab' },
  { name: "Blooth Pink", hex: '#E7AA9E', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blooth-pink' },
  { name: "Fruit Fool", hex: '#C98B84', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/fruit-fool' },
  { name: "Crimson Red", hex: '#AF7A7B', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/crimson-red' },
  { name: "Book Room Red", hex: '#AC6E60', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/book-room-red' },
  { name: "Lake Red", hex: '#C05270', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lake-red' },
  { name: "Bisque", hex: '#E17D67', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bisque' },
  { name: "Copenhagen Roof", hex: '#C7614F', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/copenhagen-roof' },
  { name: "Harissa", hex: '#AA4D3D', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/harissa' },
  { name: "Blazer", hex: '#B2534C', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/blazer' },
  { name: "Terre d' Egypte", hex: '#A65A4F', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/terre-d-egypte' },
  { name: "Radicchio", hex: '#954C53', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/radicchio' },
  { name: "Potted Shrimp", hex: '#DAC1B1', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/potted-shrimp' },
  { name: "Smoked Trout", hex: '#C4AE9A', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/smoked-trout' },
  { name: "Pink Cup", hex: '#E8B9A5', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pink-cup' },
  { name: "Dutch Pink", hex: '#D8B592', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dutch-pink' },
  { name: "Mortar Pink", hex: '#DBBC9B', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/mortar-pink' },
  { name: "Faded Terracotta", hex: '#E2BB9D', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/faded-terracotta' },
  { name: "Fake Tan", hex: '#D4AD8E', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/fake-tan' },
  { name: "Entrance Hall Pink", hex: '#C8A488', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/entrance-hall-pink' },
  { name: "Fowler Pink", hex: '#D9AD8E', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/fowler-pink' },
  { name: "Ointment Pink", hex: '#CB9F86', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ointment-pink' },
  { name: "Menagerie", hex: '#D2977A', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/menagerie' },
  { name: "Folly Pink", hex: '#C48F73', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/folly-pink' },
  { name: "Porphyry Pink", hex: '#B98274', category: 'Pinks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/porphyry-pink' },
  { name: "Loggia", hex: '#B06F5E', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/loggia' },
  { name: "Singed Red", hex: '#A05E50', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/singed-red' },
  { name: "Fox Red", hex: '#B07A64', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/fox-red' },
  { name: "Deep Reddish Brown", hex: '#714A42', category: 'Reds', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/deep-reddish-brown' },
  { name: "House White", hex: '#EFE5CA', category: 'Whites', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/house-white' },
  { name: "Pale Hound", hex: '#E2DBB3', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pale-hound' },
  { name: "Bombazine", hex: '#EAD9AE', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bombazine' },
  { name: "Hound Lemon", hex: '#E6D8AC', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hound-lemon' },
  { name: "Gervase Yellow", hex: '#E3D296', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/gervase-yellow' },
  { name: "Churlish Green", hex: '#CFC68F', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/churlish-green' },
  { name: "Lancaster Yellow", hex: '#F1EBBA', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/lancaster-yellow' },
  { name: "Butterweed", hex: '#E9E28A', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/butterweed' },
  { name: "Citrona", hex: '#E2D27F', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/citrona' },
  { name: "Yellowcake", hex: '#E9E066', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/yellowcake' },
  { name: "Sherbert Lemon", hex: '#F9E38D', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sherbert-lemon' },
  { name: "Ciara Yellow", hex: '#E7CA85', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ciara-yellow' },
  { name: "Corngold", hex: '#E7C673', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/corngold' },
  { name: "Orangery", hex: '#E2B372', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/orangery' },
  { name: "Straw", hex: '#DCBC88', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/straw' },
  { name: "Print Room Yellow", hex: '#DDBC7E', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/print-room-yellow' },
  { name: "Octagon Yellow", hex: '#D5B57B', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/octagon-yellow' },
  { name: "Cane", hex: '#C69B60', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cane' },
  { name: "Dutch Orange", hex: '#E8A648', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dutch-orange' },
  { name: "Sand", hex: '#C1996C', category: 'Yellows', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sand' },
  { name: "Wet Sand", hex: '#BE9062', category: 'Oranges', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/wet-sand' },
  { name: "Tunsgate Green", hex: '#E9E8D1', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/tunsgate-green' },
  { name: "Acid Drop", hex: '#C3C668', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/acid-drop' },
  { name: "Emerald Green", hex: '#7BA979', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/emerald-green' },
  { name: "Palm", hex: '#C9D3C0', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/palm' },
  { name: "Pea Green", hex: '#779070', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pea-green' },
  { name: "Suffield Green", hex: '#92A488', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/suffield-green' },
  { name: "Folly Green", hex: '#87A27C', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/folly-green' },
  { name: "Saxon Green", hex: '#9EAD86', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/saxon-green' },
  { name: "Sutcliffe Green", hex: '#8C9A7B', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sutcliffe-green' },
  { name: "Dyrehaven", hex: '#6C7A66', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dyrehaven' },
  { name: "Minster Green", hex: '#5C6A58', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/minster-green' },
  { name: "Danish Lawn", hex: '#428750', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/danish-lawn' },
  { name: "Verdigris Green", hex: '#408B6D', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/verdigris-green' },
  { name: "Pond Green", hex: '#A6B5AB', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pond-green' },
  { name: "Chappell Green", hex: '#96AB9E', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/chappell-green' },
  { name: "Castle Gray", hex: '#919E94', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/castle-gray' },
  { name: "Pavilion Blue", hex: '#DEE5DB', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pavilion-blue' },
  { name: "Middle Ground", hex: '#C3D4CC', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/middle-ground' },
  { name: "Ancona Blue", hex: '#A8C0BC', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ancona-blue' },
  { name: "Powder Blue", hex: '#ADC0BA', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/powder-blue' },
  { name: "Ballroom Blue", hex: '#94AFAD', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ballroom-blue' },
  { name: "Sugar Bag Light", hex: '#86A6A2', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sugar-bag-light' },
  { name: "Mere Green", hex: '#4A7676', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/mere-green' },
  { name: "Coppice Blue", hex: '#4D6B71', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/coppice-blue' },
  { name: "Sloe Blue", hex: '#5F7E89', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/sloe-blue' },
  { name: "Berrington Blue", hex: '#829A9E', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/berrington-blue' },
  { name: "Barrow Blue", hex: '#738488', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/barrow-blue' },
  { name: "Yonder", hex: '#93B6C4', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/yonder' },
  { name: "St Giles Blue", hex: '#5DA4C6', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/st-giles-blue' },
  { name: "Graupel", hex: '#BCCBE7', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/graupel' },
  { name: "Hazy", hex: '#B4C7CC', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/hazy' },
  { name: "Bay Area Blue", hex: '#87B0CE', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bay-area-blue' },
  { name: "Bothy Blue", hex: '#87A1CC', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bothy-blue' },
  { name: "Pitch Blue", hex: '#536283', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/pitch-blue' },
  { name: "Chinese Blue", hex: '#6E96A9', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/chinese-blue' },
  { name: "Yard Blue", hex: '#6993A6', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/yard-blue' },
  { name: "Belvedere Blue", hex: '#648EA9', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/belvedere-blue' },
  { name: "Ultra Marine Blue", hex: '#5E80A2', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/ultra-marine-blue' },
  { name: "Dinnerware", hex: '#4A628B', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/dinnerware' },
  { name: "Drawing Room Blue", hex: '#485476', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/drawing-room-blue' },
  { name: "Imperial Purple", hex: '#565771', category: 'Purples', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/imperial-purple' },
  { name: "Serge", hex: '#45506D', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/serge' },
  { name: "Bible Black", hex: '#4B4859', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/bible-black' },
  { name: "Titmouse Blue", hex: '#434351', category: 'Blues', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/titmouse-blue' },
  { name: "Mahogany", hex: '#544948', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/mahogany' },
  { name: "Cola", hex: '#524542', category: 'Browns', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/cola' },
  { name: "Tar", hex: '#5A5A5A', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/tar' },
  { name: "Smelt Black", hex: '#404040', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/smelt-black' },
  { name: "Beetle Black", hex: '#5E6363', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/beetle-black' },
  { name: "Grate Black", hex: '#403E3C', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/grate-black' },
  { name: "Black Blue", hex: '#424649', category: 'Blacks', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/black-blue' },
  { name: "Duck Green", hex: '#435545', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/duck-green' },
  { name: "Monkey Puzzle", hex: '#4F5D5A', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/monkey-puzzle' },
  { name: "Grove Green", hex: '#475552', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/grove-green' },
  { name: "Chine Green", hex: '#495651', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/chine-green' },
  { name: "Carriage Green", hex: '#47534C', category: 'Greens', tone: 'Mid', brand: 'Farrow & Ball', link: 'https://www.farrow-ball.com/paint/carriage-green' },
];
